#!/usr/bin/env bash

# SCRIPT_NAME="cec-toolbox"
DEVICE_NAME="PC"
EXE="cec-ctl -st0"
COMMAND=$1

configure_playback() {
    $EXE --playback -o "$1"
    sleep .2s
}

get_physical_address() {
    $EXE -x
}

switch_input() {
    [[ -z "$1" ]] && return 1
    $EXE --active-source phys-addr="$1"
}

get_tv_state() {
    $EXE --give-device-power-status | grep -c "pwr-state: on"
}

tv_on() {
    configure_playback "$DEVICE_NAME"
    [[ "$(get_tv_state)" -eq 0 ]] && $EXE --image-view-on
    switch_input "$(get_physical_address)"
}

tv_off() {
    configure_playback "$DEVICE_NAME"
    [[ "$(get_tv_state)" -ne 0 ]] && $EXE --standby
}

case "$COMMAND" in
    "on")
        tv_on
        ;;
    "off")
        tv_off
        ;;
    "input")
        switch_input "${2}.0.0.0"
        ;;
    "get-input")
        get_physical_address | cut -d "." -f 1
        ;;
    "address")
        get_physical_address
        ;;
    "configure")
        configure_playback "$DEVICE_NAME"
        ;;
    *)
        echo "Unknwon command: $COMMAND"
        ;;
esac
